import { createClientFromRequest } from 'npm:@base44/sdk@0.8.4';
import { jsPDF } from 'npm:jspdf@2.5.1';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { data_call_ids, options = {} } = await req.json();

    if (!data_call_ids || data_call_ids.length === 0) {
      return Response.json({ error: 'No data calls specified' }, { status: 400 });
    }

    const doc = new jsPDF();
    let yPosition = 20;
    const pageHeight = doc.internal.pageSize.height;
    const margin = 20;

    const addText = (text, fontSize = 10, isBold = false) => {
      if (yPosition > pageHeight - margin) {
        doc.addPage();
        yPosition = 20;
      }
      doc.setFontSize(fontSize);
      doc.setFont(undefined, isBold ? 'bold' : 'normal');
      doc.text(text, margin, yPosition);
      yPosition += fontSize / 2 + 2;
    };

    const addSection = (title) => {
      yPosition += 5;
      addText(title, 14, true);
      yPosition += 3;
    };

    // Cover page
    addText('Data Call Export Report', 20, true);
    yPosition += 5;
    addText(`Generated: ${new Date().toLocaleDateString()}`, 10);
    addText(`Generated by: ${user.full_name}`, 10);
    yPosition += 10;

    // Process each data call
    for (let i = 0; i < data_call_ids.length; i++) {
      const dataCallId = data_call_ids[i];
      
      // Fetch data call
      const dataCalls = await base44.asServiceRole.entities.DataCallRequest.filter({ id: dataCallId });
      const dataCall = dataCalls[0];
      
      if (!dataCall) continue;

      if (i > 0) {
        doc.addPage();
        yPosition = 20;
      }

      // Header
      addSection(`Data Call ${i + 1}: ${dataCall.request_title}`);
      
      // Metadata
      addText(`Status: ${dataCall.overall_status}`, 10);
      addText(`Priority: ${dataCall.priority}`, 10);
      addText(`Recipient: ${dataCall.assigned_to_name || dataCall.assigned_to_email}`, 10);
      addText(`Due Date: ${dataCall.due_date || 'Not set'}`, 10);
      addText(`Created: ${new Date(dataCall.created_date).toLocaleDateString()}`, 10);
      
      if (dataCall.sent_date) {
        addText(`Sent: ${new Date(dataCall.sent_date).toLocaleDateString()}`, 10);
      }
      
      if (dataCall.completed_date) {
        addText(`Completed: ${new Date(dataCall.completed_date).toLocaleDateString()}`, 10);
      }

      yPosition += 5;

      // Description
      if (dataCall.request_description) {
        addSection('Description');
        const descLines = doc.splitTextToSize(dataCall.request_description, 170);
        descLines.forEach(line => addText(line, 10));
      }

      yPosition += 5;

      // Checklist
      addSection('Checklist Items');
      (dataCall.checklist_items || []).forEach((item, idx) => {
        const status = item.status === 'completed' ? '✓' : '○';
        const required = item.is_required ? '(Required)' : '(Optional)';
        
        addText(`${status} ${idx + 1}. ${item.item_label} ${required}`, 10, true);
        
        if (item.item_description) {
          const descLines = doc.splitTextToSize(item.item_description, 160);
          descLines.forEach(line => {
            addText(`   ${line}`, 9);
          });
        }
        
        if (options.includeFiles && item.uploaded_files?.length > 0) {
          addText(`   Files: ${item.uploaded_files.length} uploaded`, 9);
        }
        
        yPosition += 3;
      });

      // Progress Summary
      const totalItems = dataCall.checklist_items?.length || 0;
      const completedItems = dataCall.checklist_items?.filter(i => i.status === 'completed').length || 0;
      const progressPct = totalItems > 0 ? Math.round((completedItems / totalItems) * 100) : 0;
      
      yPosition += 5;
      addSection('Progress Summary');
      addText(`Completed: ${completedItems} / ${totalItems} items (${progressPct}%)`, 10);
    }

    // Generate PDF
    const pdfBytes = doc.output('arraybuffer');

    return new Response(pdfBytes, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="data-calls-export-${new Date().toISOString().split('T')[0]}.pdf"`
      }
    });

  } catch (error) {
    console.error('PDF export error:', error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});