import React, { useState, useEffect } from 'react';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Sparkles, Edit3, History } from 'lucide-react';
import { cn } from '@/lib/utils';

/**
 * NarrativeInput Component
 * Reusable text area with AI-edit tracking for audit trail
 * 
 * Props:
 * - label: field label
 * - value: current text value
 * - onChange: callback with updated value
 * - placeholder: placeholder text
 * - rows: number of textarea rows
 * - isAIGenerated: whether this was originally AI-generated
 * - fieldName: unique field identifier for tracking
 * - required: whether field is required
 * - maxLength: maximum character length
 * - onEditTracked: callback to track user edits for audit trail
 */
export default function NarrativeInput({ 
    label, 
    value = '', 
    onChange, 
    placeholder, 
    rows = 4,
    isAIGenerated = false,
    fieldName,
    required = false,
    maxLength,
    onEditTracked
}) {
    const [hasBeenEdited, setHasBeenEdited] = useState(false);
    const [originalAIValue, setOriginalAIValue] = useState('');
    const [editHistory, setEditHistory] = useState([]);

    // Track original AI value when component mounts with AI-generated content
    useEffect(() => {
        if (isAIGenerated && value && !originalAIValue) {
            setOriginalAIValue(value);
        }
    }, [isAIGenerated, value, originalAIValue]);

    // Handle user edits
    const handleChange = (newValue) => {
        onChange(newValue);

        // Track that user has edited AI content
        if (isAIGenerated && !hasBeenEdited && newValue !== originalAIValue) {
            setHasBeenEdited(true);
            
            // Create edit record for audit trail
            const editRecord = {
                field_name: fieldName,
                original_value: originalAIValue,
                user_edited_value: newValue,
                edited_at: new Date().toISOString()
            };

            setEditHistory([...editHistory, editRecord]);

            // Notify parent component for centralized tracking
            if (onEditTracked) {
                onEditTracked(editRecord);
            }
        }
    };

    // Show edit history badge
    const showEditIndicator = isAIGenerated && hasBeenEdited;

    return (
        <div className="space-y-2">
            <Label className="flex items-center justify-between">
                <span className="flex items-center gap-2">
                    {label}
                    {required && <span className="text-red-500">*</span>}
                    {isAIGenerated && !hasBeenEdited && (
                        <Badge variant="secondary" className="text-xs">
                            <Sparkles className="w-3 h-3 mr-1" />
                            AI Generated
                        </Badge>
                    )}
                    {showEditIndicator && (
                        <Badge variant="outline" className="text-xs border-blue-500 text-blue-700">
                            <Edit3 className="w-3 h-3 mr-1" />
                            User Edited
                        </Badge>
                    )}
                </span>
                {maxLength && (
                    <span className={cn(
                        "text-xs",
                        value.length > maxLength ? "text-red-500 font-semibold" : "text-slate-500"
                    )}>
                        {value.length}/{maxLength}
                    </span>
                )}
            </Label>
            <Textarea
                value={value}
                onChange={(e) => handleChange(e.target.value)}
                placeholder={placeholder}
                rows={rows}
                maxLength={maxLength}
                className={cn(
                    "resize-y",
                    isAIGenerated && !hasBeenEdited && "bg-blue-50 border-blue-200",
                    showEditIndicator && "bg-white border-blue-300"
                )}
            />
            {isAIGenerated && (
                <p className="text-xs text-slate-500">
                    {hasBeenEdited 
                        ? "✏️ You've edited this AI-generated content. Original version saved for audit trail."
                        : "💡 This content was generated by AI. You can edit it as needed."}
                </p>
            )}
            {editHistory.length > 0 && (
                <Button
                    variant="ghost"
                    size="sm"
                    className="text-xs text-slate-600 h-auto p-1"
                    onClick={() => {
                        // Could expand to show full edit history modal
                        alert(`Edit History:\n\nOriginal (AI): ${originalAIValue.substring(0, 100)}...\n\nCurrent: ${value.substring(0, 100)}...`);
                    }}
                >
                    <History className="w-3 h-3 mr-1" />
                    View Edit History ({editHistory.length})
                </Button>
            )}
        </div>
    );
}